package nvnteam.guessthesketch;

import java.util.Random;

public class WordBase 
{
    private final static Random m_randGen = new Random();
    private static String[] m_easyWords = new String[] 
            {
                "CAT",
                "SUN",
                "CUP",
                "GHOST",
                "FLOWER",
                "PIE",
                "COW",
                "BANANA",
                "SNOWFLAKE",
                "BUG",
                "BOOK",
                "JAR",
				"SNAKE",
				"LIGHT",
				"TREE",
				"LIPS",
				"APPLE",
				"SLIDE",
				"SOCKS",
				"SMILE",
				"SWING",
				"COAT",
				"SHOE",
				"WATER",
				"HEART",
				"HAT",
				"OCEAN",
				"KITE",
				"DOG",
				"MOUTH",
				"MILK",
				"DUCK",
				"EYES",
				"SKATEBOARD",
				"BIRD",
				"BOY",
				"PERSON",
				"GIRL",
				"MOUSE",
				"BALL",
				"HOUSE",
				"STAR",
				"NOSE",
				"BED",
				"WHALE",
				"JACKET",
				"SHIRT",
				"HIPPO",
				"BEACH",
				"EGG",
				"FACE",
				"COOKIE",
				"CHEESE",
				"ICE CREAM CONE",
				"DRUM",
				"CIRCLE",
				"SPOON",
				"WORM",
				"SPIDER WEB"
            };
    
    private static String[] m_mediumWords = new String[]
            {
                "PASSWORD",
				"HORSE",
				"DOOR",
				"SONG",
				"TRIP",
				"BACKBONE",
				"BOMB",
				"ROUND",
				"TREASURE",
				"GARBAGE",
				"PARK",
				"PIRATE",
				"SKI",
				"STATE",
				"WHISTLE",
				"PALACE",
				"BASEBALL",
				"COAL",
				"QUEEN",
				"DOMINOES",
				"PHOTOGRAPH",
				"COMPUTER",
				"HOCKEY",
				"AIRCRAFT",
				"HOT DOG",
				"SALT AND PEPPER",
				"KEY",
				"IPAD",
				"WHISK",
				"FROG",
				"LAWNMOWER",
				"MATTRESS",
				"PINWHEEL",
				"CAKE",
				"CIRCUS",
				"BATTERY",
				"MAILMAN",
				"COWBOY",
				"BICYCLE",
				"SKATE",
				"ELECTRICITY",
				"LIGHTSABER",
				"THIEF",
				"TEAPOT",
				"DEEP",
				"SPRING",
				"NATURE",
				"SHALLOW",
				"TOAST",
				"OUTSIDE",
				"AMERICA",
				"ROLLER BLADING",
				"GINGERBREAD MAN",
				"BOWTIE",
				"HALF",
				"SPARE",
				"WAX",
				"LIGHT BULB",
				"PLATYPUS",
				"MUSIC"
            };
    
    private static String[] m_hardWords = new String[]
            {
                "LANDSCAPE",
				"SNAG",
				"JUNGLE",
				"IMPORTANT",
				"MIME",
				"PEASANT",
				"BAGGAGE",
				"HAIL",
				"CLOG",
				"PIZZA SAUCE",
				"PASSWORD",
				"HEINZ 57",
				"SCREAM",
				"NEWSLETTER",
				"BOOKEND",
				"PRO",
				"DRIPPING",
				"PHARMACIST",
				"LIE",
				"CATALOG",
				"RINGLEADER",
				"HUSBAND",
				"LASER",
				"DIAGONAL",
				"COMFY",
				"MYTH",
				"DORSAL",
				"BISCUIT",
				"HYDROGEN",
				"MACARONI",
				"RUBBER",
				"DARKNESS",
				"YOLK",
				"EXERCISE",
				"VEGETARIAN",
				"SHREW",
				"CHESTNUT",
				"DITCH",
				"WOBBLE",
				"GLITTER",
				"NEIGHBORHOOD",
				"DIZZY",
				"FIRESIDE",
				"RETAIL",
				"DRAWBACK",
				"LOGO",
				"FABRIC",
				"MIRROR",
				"BARBER",
				"JAZZ",
				"MIGRATE",
				"DROUGHT",
				"COMMERCIAL",
				"DASHBOARD",
				"BARGAIN",
				"DOUBLE",
				"DOWNLOAD",
				"PROFESSOR",
				"SKI GOGGLES",
				"VITAMIN"
            };
    
	 private static String[] m_reallyHardWords = new String[]
			 {
				"VASION",
				"LOITERER",
				"OBSERVATORY",
				"CENTURY",
				"ATLANTIS",
				"KILOGRAM",
				"NEUTRON",
				"STOWAWAY",
				"PHYCHOLOGIST",
				"EXPONENTIAL",
				"ARISTOCRAT",
				"EUREKA",
				"PARODY",
				"CARTOGRAPHY",
				"FIGMENT",
				"PHILOSOPHER",
				"TINTING",
				"OVERTURE",
				"OPAQUE",
				"EVERGLADES",
				"IRONIC",
				"ZERO",
				"LANDFILL",
				"IMPLODE",
				"CZAR",
				"ARMADA",
				"CRISP",
				"STOCKHOLDER",
				"INQUISTION",
				"MOOCH",
				"GALLOP",
				"ARCHAEOLOGIST",
				"BLACKSMITH",
				"ADDENDUM",
				"UPGRADE",
				"HANG TEN",
				"ACRE",
				"TWANG",
				"MINE CAR",
				"PROTESTANT",
				"BRUNETTE",
				"STOUT",
				"QUARANTINE",
				"TUTOR",
				"POSITIVE",
				"CHAMPION",
				"PASTRY",
				"TOURNAMENT",
				"CHICK-FIL-A",
				"RAINWATER",
				"RANDOM",
				"LYRICS",
				"ICE FISHING",
				"CLUE",
				"FLUTTER",
				"SLUMP",
				"LIGAMENT",
				"FLOTSAM",
				"SIESTA",
				"POMP"
			 };
	
    public static String getEasyWord()
    {
        return m_easyWords[m_randGen.nextInt(m_easyWords.length)];
    }
    
    public static String getMediumWord()
    {
        return m_mediumWords[m_randGen.nextInt(m_mediumWords.length)];
    }
    
    public static String getHardWord()
    {
        return m_hardWords[m_randGen.nextInt(m_hardWords.length)];
    }
	
	 public static String getReallyHardWord()
    {
        return m_reallyHardWords[m_randGen.nextInt(m_reallyHardWords.length)];
    }
}
